### ISSUE TITLE
Installation Apache Airflow in Kubernetes 

### ISSUE THREAD

**Issue by niklasden** [kirenz/data-architecture-mlops#1]
Hallo @kirenz,

Bei der Installation von Apache Airflow in einem Kubernetes Cluster kommt es zu einem Time-Out Fehler beim Starten des "airflow-run-airflow-migrations" pods.
Es gab dazu bereits im AirFlow Repo Issue, der dort vorhandene Fix scheint jedoch in der aktuellen Airflow nichtmehr zu funktionieren. Ich habe daher dort mal das eigentlich geschlossene Issue kommentiert, vgl.  https://github.com/apache/airflow/issues/16176#issuecomment-951929699

Meine Frage wäre nun, ob es bei den anderen Gruppen beim Deployen von AirFlow zu ähnlichen Problemen gekommen ist?
![Bildschirmfoto 2021-10-26 um 16 21 52](https://user-images.githubusercontent.com/43001868/138898904-a2365182-b6d0-4aa5-bacf-a780b8f26788.png)

Infos zum Kubernetes Cluster:
Ubuntu 20.04 
MicroK8s
Apache Airflow Version: 1.2.0
Installation nach den offiziellen Docs unter: https://airflow.apache.org/docs/helm-chart/stable/index.html#installing-the-chart

**Comment by kirenz** [comment]
Hallo @niklasden,

vielen Dank für den Hinweis. Mir ist aufgefallen, dass Sie eine sehr alte Version von Airflow nutzen (1.2.0). Die aktuellste Version von Airflow ist bereits 2.2.0 (2021-10-11). 

Ich habe zwischenzeitlich bei Google Credits beantragt und hoffe, dass wir zeitnah in der Cloud weiterentwickeln können. Dann sollte auch die Erstellung der Infrastruktur vereinfacht werden (siehe bspw. hier: [TFX on Cloud AI](https://www.tensorflow.org/tfx/tutorials/tfx/cloud-ai-platform-pipelines)). Falls sich die Bereitstellung zu lange verzögern sollte, werde ich ein Tutorial für die lokale Installation der zentralen Komponenten bereitstellen. In diesem Fall würde ich auch noch einen Vorlesungstermin zu der Thematik anbieten.

**Comment by niklasden** [comment]
Hallo @kirenz,

die Versionen habe ich leider etwas verwirrend formuliert, um Airflow über den Packagemanager Helm zu installieren bezieht man aktuell die Version 1.2.0 des Airflow Helm Charts, welches eigentlich die aktuellste Version von Airflow enthält. (siehe https://airflow.apache.org/docs/helm-chart/stable/index.html)

Mein konkreten Fehler konnte ich durch das Wechseln auf minikube anstelle von microk8s für die Kubernetes Umgebung beheben.
Danke für das bereitstellen der Google Credits 👍
